# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-04 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('query_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_owner', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, default=-1, null=True)),
                ('msg', models.CharField(blank=True, max_length=200, null=True)),
                ('src_status', models.IntegerField(blank=True, default=0, null=True)),
                ('src_msg', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('authority', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('permit_province', models.CharField(blank=True, max_length=300, null=True)),
                ('number_limit', models.IntegerField(default=0)),
                ('number_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xh', models.CharField(blank=True, max_length=15, null=True)),
                ('hpzl', models.CharField(blank=True, max_length=2, null=True)),
                ('hphm', models.CharField(blank=True, max_length=15, null=True)),
                ('clpp1', models.CharField(blank=True, max_length=35, null=True)),
                ('clxh', models.CharField(blank=True, max_length=35, null=True)),
                ('clpp2', models.CharField(blank=True, max_length=35, null=True)),
                ('gcjk', models.CharField(blank=True, max_length=1, null=True)),
                ('zzg', models.CharField(blank=True, max_length=3, null=True)),
                ('zzcmc', models.CharField(blank=True, max_length=65, null=True)),
                ('clsbdh', models.CharField(blank=True, max_length=25, null=True)),
                ('fdjh', models.CharField(blank=True, max_length=30, null=True)),
                ('cllx', models.CharField(blank=True, max_length=3, null=True)),
                ('csys', models.CharField(blank=True, max_length=5, null=True)),
                ('syxz', models.CharField(blank=True, max_length=1, null=True)),
                ('syr', models.CharField(blank=True, max_length=128, null=True)),
                ('ccdjrq', models.CharField(blank=True, max_length=30, null=True)),
                ('djrq', models.CharField(blank=True, max_length=30, null=True)),
                ('yxqz', models.CharField(blank=True, max_length=30, null=True)),
                ('qzbfqz', models.CharField(blank=True, max_length=30, null=True)),
                ('fzjg', models.CharField(blank=True, max_length=10, null=True)),
                ('glbm', models.CharField(blank=True, max_length=150, null=True)),
                ('bxzzrq', models.CharField(blank=True, max_length=30, null=True)),
                ('zt', models.CharField(blank=True, max_length=10, null=True)),
                ('dybj', models.CharField(blank=True, max_length=1, null=True)),
                ('fdjxh', models.CharField(blank=True, max_length=65, null=True)),
                ('rlzl', models.CharField(blank=True, max_length=5, null=True)),
                ('pl', models.CharField(blank=True, max_length=30, null=True)),
                ('gl', models.CharField(blank=True, max_length=30, null=True)),
                ('zxxs', models.CharField(blank=True, max_length=1, null=True)),
                ('cwkc', models.CharField(blank=True, max_length=30, null=True)),
                ('cwkk', models.CharField(blank=True, max_length=30, null=True)),
                ('cwkg', models.CharField(blank=True, max_length=30, null=True)),
                ('hxnbcd', models.CharField(blank=True, max_length=30, null=True)),
                ('hxnbkd', models.CharField(blank=True, max_length=30, null=True)),
                ('hxnbgd', models.CharField(blank=True, max_length=30, null=True)),
                ('gbthps', models.CharField(blank=True, max_length=30, null=True)),
                ('zs', models.CharField(blank=True, max_length=30, null=True)),
                ('zj', models.CharField(blank=True, max_length=30, null=True)),
                ('qlj', models.CharField(blank=True, max_length=30, null=True)),
                ('hlj', models.CharField(blank=True, max_length=30, null=True)),
                ('ltgg', models.CharField(blank=True, max_length=65, null=True)),
                ('lts', models.CharField(blank=True, max_length=30, null=True)),
                ('zzl', models.CharField(blank=True, max_length=30, null=True)),
                ('zbzl', models.CharField(blank=True, max_length=30, null=True)),
                ('hdzzl', models.CharField(blank=True, max_length=30, null=True)),
                ('hdzk', models.CharField(blank=True, max_length=30, null=True)),
                ('zqyzl', models.CharField(blank=True, max_length=30, null=True)),
                ('qpzk', models.CharField(blank=True, max_length=30, null=True)),
                ('hpzk', models.CharField(blank=True, max_length=30, null=True)),
                ('hbdbqk', models.CharField(blank=True, max_length=130, null=True)),
                ('ccrq', models.CharField(blank=True, max_length=30, null=True)),
                ('clyt', models.CharField(blank=True, max_length=2, null=True)),
                ('ytsx', models.CharField(blank=True, max_length=1, null=True)),
                ('xszbh', models.CharField(blank=True, max_length=30, null=True)),
                ('jyhgbzbh', models.CharField(blank=True, max_length=30, null=True)),
                ('xzqh', models.CharField(blank=True, max_length=30, null=True)),
                ('zsxzqh', models.CharField(blank=True, max_length=30, null=True)),
                ('zzxzqh', models.CharField(blank=True, max_length=30, null=True)),
                ('sgcssbwqk', models.CharField(blank=True, max_length=4000, null=True)),
                ('sfmj', models.CharField(blank=True, max_length=1, null=True)),
                ('bmjyy', models.CharField(blank=True, max_length=4000, null=True)),
                ('sfxny', models.CharField(blank=True, max_length=1, null=True)),
                ('xnyzl', models.CharField(blank=True, max_length=1, null=True)),
                ('bz', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loginfo',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_info.UrlInfo'),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_info.UserInfo'),
        ),
    ]
