# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginfo',
            name='vehicle_owner',
        ),
        migrations.AddField(
            model_name='loginfo',
            name='vin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
