# Generated by Django 2.2.1 on 2019-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, default=2, null=True)),
                ('vio_time', models.CharField(blank=True, max_length=30, null=True)),
                ('vio_position', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_point', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_money', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vio_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_status', models.IntegerField(blank=True, default=-1, null=True)),
                ('pay_status', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.IntegerField(blank=True, default=1, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_query.UserInfo')),
            ],
        ),
    ]
