# Generated by Django 2.2.1 on 2019-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_query', '0002_auto_20190521_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_activity',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vehicle_number',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_loc',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_money',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_code',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_point',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vio_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='vioinfo',
            old_name='vehicle_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='status',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='type',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
