# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('authority', models.IntegerField(blank=True, default=1, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.IntegerField(blank=True, default=2, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, default=-1, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_query.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.IntegerField(blank=True, default=2, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.IntegerField(blank=True, default=0, null=True)),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('loc', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_status', models.IntegerField(blank=True, default=-1, null=True)),
                ('pay_status', models.IntegerField(blank=True, default=-1, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_query.UserInfo')),
            ],
        ),
    ]
