# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_query', '0003_vioinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='limitation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='queried_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
