# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_api_tsn', '0003_userinfo_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default='2099-2-24 00:00:00')),
                ('response_time', models.DateTimeField(default='2099-2-24 00:00:00')),
                ('v_number', models.CharField(max_length=20)),
                ('v_type', models.CharField(max_length=10)),
            ],
        ),
    ]
