# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocInfo',
            fields=[
                ('loc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=20)),
                ('short_name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
                ('authority', models.IntegerField(default=0)),
                ('is_valid', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('engine_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField()),
                ('opt_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vio_sch.LocInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.VehicleType'),
        ),
        migrations.AddField(
            model_name='locinfo',
            name='url_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UrlInfo'),
        ),
    ]
