# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locinfo',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='query_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='locinfo',
            name='loc_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locinfo',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='locinfo',
            name='url_id',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UrlInfo'),
        ),
        migrations.AlterField(
            model_name='urlinfo',
            name='url_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='opt_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.LocInfo'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.VehicleType'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
