# Generated by Django 2.0.6 on 2018-06-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
