# Generated by Django 2.0.6 on 2018-06-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0002_auto_20180610_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('engine_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField()),
                ('opt_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vio_sch.Location')),
                ('vehicle_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.Type')),
            ],
        ),
    ]
