# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0002_auto_20180624_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locinfo',
            old_name='plate',
            new_name='plate_name',
        ),
        migrations.RemoveField(
            model_name='locinfo',
            name='short_name',
        ),
    ]
