# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0004_auto_20180626_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=-1, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UrlInfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=10, null=True)),
                ('vio_time', models.DateTimeField(blank=True, null=True)),
                ('vio_position', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_point', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_money', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vio_loc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='opt_loc',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='query_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.VehicleInfo'),
        ),
    ]
