# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0006_auto_20180626_1354'),
        ('vio_sch', '0004_auto_20180625_2343'),
    ]

    operations = [
    ]
