# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0006_auto_20180626_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vioinfo',
            name='vio_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
