# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0007_auto_20180628_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
