# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0008_auto_20180629_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginfo',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='loginfo',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
