# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0009_auto_20180704_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
