# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0010_loginfo_ip'),
        ('vio_sch', '0007_merge_20180707_1839'),
    ]

    operations = [
    ]
