# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0012_auto_20180707_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
