# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0013_userinfo_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locinfo',
            old_name='url_id',
            new_name='url',
        ),
    ]
