# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0014_auto_20180713_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
