# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0016_auto_20180715_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, default=2, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_code', models.CharField(blank=True, max_length=50, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UserInfo'),
        ),
    ]
