# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0017_auto_20180716_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='create_time',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
