# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0019_auto_20180726_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='spider_status',
            field=models.IntegerField(default=0),
        ),
    ]
