# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0020_vehicleinfo_spider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='spider_status',
            field=models.BooleanField(default=False),
        ),
    ]
