# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0021_auto_20180809_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfoSz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, default=2, null=True)),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(default=99)),
                ('msg', models.CharField(blank=True, max_length=50, null=True)),
                ('spider_status', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('query_counter', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VioInfoSz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, default=2, null=True)),
                ('vio_time', models.CharField(blank=True, max_length=30, null=True)),
                ('vio_position', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_point', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_money', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vio_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_status', models.IntegerField(blank=True, default=-1, null=True)),
                ('pay_status', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
    ]
