# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0023_auto_20190623_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='VioCode',
            fields=[
                ('vio_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vio_activity', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_point', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_money', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
