# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-26 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0024_viocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocUrlRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.LocInfo')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UrlInfo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vio_sch.UserInfo')),
            ],
        ),
    ]
