# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0025_locurlrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='number_limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='number_used',
            field=models.IntegerField(default=0),
        ),
    ]
