# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0026_auto_20190903_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='is_cache',
            field=models.BooleanField(default=False),
        ),
    ]
