# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0026_auto_20190903_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginfo',
            name='engine_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='is_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginfo',
            name='vehicle_type',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 21, 5, 24, 729194)),
        ),
    ]
