# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-08 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0027_auto_20191108_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 21, 11, 43, 386565)),
        ),
    ]
