# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-24 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0028_auto_20191211_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='VioInfoAvisIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.IntegerField(blank=True, default=2, null=True)),
                ('vio_time', models.CharField(blank=True, max_length=30, null=True)),
                ('vio_position', models.CharField(blank=True, max_length=100, null=True)),
                ('vio_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('vio_point', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_money', models.IntegerField(blank=True, default=0, null=True)),
                ('vio_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vio_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('deal_status', models.IntegerField(blank=True, default=-1, null=True)),
                ('pay_status', models.IntegerField(blank=True, default=-1, null=True)),
            ],
        ),
    ]
