# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-27 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vio_sch', '0029_auto_20200324_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfoAvisIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
